version: 1
disable_existing_loggers: false # Important, otherwise some lib logs may be dropped
formatters:
    standard:
        format: '[%(asctime)s][%(threadName)s][%(name)s.%(funcName)s:%(lineno)d][%(levelname)s] %(message)s'
    raw_rcon:
        format: '%(message)s'
handlers:
    default_stream_handler:
        class: logging.StreamHandler
        formatter: standard
        level: INFO
        stream: ext://sys.stdout
    default_file_handler:
        backupCount: 5
        class: logging.handlers.RotatingFileHandler
        filename: rcon.log
        formatter: standard
        level: DEBUG
    raw_rcon_file_handler:
        backupCount: 5
        class: logging.handlers.RotatingFileHandler
        filename: raw_rcon.log
        formatter: raw_rcon
        level: DEBUG
    error_file_handler:
        backupCount: 5
        class: logging.handlers.RotatingFileHandler
        delay: true
        filename: rcon_error.log
        formatter: standard
        level: ERROR
loggers:
    '': # The root logger, best to leave it undefined (don't enter a string)
        handlers:
            - default_stream_handler
            - default_file_handler
            - error_file_handler
        level: DEBUG
        propagate: false
    'raw_rcon': # Defined to capture RCON logs
        handlers:
            - raw_rcon_file_handler
        level: DEBUG
        propagate: false